name: Translation Issue Report
description: File a translation issue report
title: "[Typo]: "
labels: ["translation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this translation issue report!
  - type: input
    id: version
    attributes:
      label: Python Version
      description: Which version of the Python documentation covers this issue?
      placeholder: ex. 3.12
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Docs Page
      description: What is the url of the page containing the issue?
      placeholder: https://docs.python.org/3/about.html
    validations:
      required: true
  - type: textarea
    id: ru-original
    attributes:
      label: Original Translation
      description: Which translated paragraph in Russian contains the issue?
    validations:
      required: true
  - type: textarea
    id: en-original
    attributes:
      label: Original Docs Paragraph
      description: Which original paragraph in English contains the issue?
    validations:
      required: false
  - type: textarea
    id: ru-suggested
    attributes:
      label: Suggested Fix
      description: What is your suggested fix?
    validations:
      required: true
